const getters = {
  materialInfo: state => state.material.dataInfo,
  authorInfo: state => state.material.authorInfo,
  authorType: state => state.material.authorType,
  materialRecord: state => state.material.record,
  materialMonitor: state => state.material.monitor,
  materialStatus: state => state.material.status,
  email: state => state.user.email,
  isLogin: state => state.user.isLogin,
  pageAuth: state => state.user.pageAuth,
  menulist: state => state.menu.list,
  specialMenu:state => state.menu.specialList,
  blackList: state => state.material.blackList,
  cutImage: state => state.smart.cutImage,
  dataMonitor: state => state.kpidata.dataMonitor,
  entireMonitor: state => state.kpidata.entireMonitor,
  analyDropList: state => state.kpidata.analyDropList,
  analyData: state => state.kpidata.analyData,
  channelList: state => state.channel.channelList,
  channelType: state => state.channel.channelDrop.typeList,
  channelTag: state => state.channel.channelDrop.tagList,
  channelData: state => state.channel.channelData,
  whiteList: state => state.channel.whiteList,
  keywordList: state => state.channel.keywordList,
  channelApi: state => state.channel.channelApi,
  curvideo: state => state.material.curvideo,
}
export default getters
